import { and, eq, lte } from "drizzle-orm";

import { dbPool } from "lib/db/db";
import {
  journalEntryTable,
  journalLineTable,
  recurringTransactionTable,
} from "lib/db/schema";
import { advanceDate } from "./advanceDate";

import type {
  InsertJournalEntry,
  InsertJournalLine,
  SelectRecurringTransaction,
} from "lib/db/schema";
import type { RecurringFrequency } from "./advanceDate";

/** Journal-entry source marking an entry generated by a recurring transaction */
const RECURRING_SOURCE = "recurring";

/** Cap on catch-up occurrences per run, so a long-dormant schedule cannot post
 * an unbounded number of entries in one pass */
const MAX_CATCHUP = 60;

interface MaterializeResult {
  recurringTransactionId: string;
  posted: number;
  nextExpectedDate: string;
}

/**
 * Post every due occurrence of a recurring transaction up to asOfDate: for each
 * scheduled date a balanced entry debits the transaction's account and credits
 * its counter account for the amount, then the schedule advances. Idempotent per
 * occurrence (source + recurringId:date), so re-running never duplicates. A
 * transaction without a counter account cannot post a balanced entry and is
 * skipped
 */
export const materializeRecurring = async (
  recurring: SelectRecurringTransaction,
  asOfDate: string,
): Promise<MaterializeResult> => {
  if (
    !recurring.isActive ||
    !recurring.counterAccountId ||
    !recurring.nextExpectedDate
  ) {
    return {
      recurringTransactionId: recurring.id,
      posted: 0,
      nextExpectedDate: recurring.nextExpectedDate?.slice(0, 10) ?? "",
    };
  }

  const counterAccountId = recurring.counterAccountId;
  let dueDate = recurring.nextExpectedDate.slice(0, 10);
  let posted = 0;

  while (dueDate <= asOfDate && posted < MAX_CATCHUP) {
    const sourceReferenceId = `${recurring.id}:${dueDate}`;

    const [existing] = await dbPool
      .select({ id: journalEntryTable.id })
      .from(journalEntryTable)
      .where(
        and(
          eq(journalEntryTable.bookId, recurring.bookId),
          eq(journalEntryTable.source, RECURRING_SOURCE),
          eq(journalEntryTable.sourceReferenceId, sourceReferenceId),
        ),
      );

    if (!existing) {
      const capturedDate = dueDate;
      await dbPool.transaction(async (tx) => {
        const [entry] = await tx
          .insert(journalEntryTable)
          .values({
            bookId: recurring.bookId,
            date: capturedDate,
            memo: recurring.name,
            source: RECURRING_SOURCE,
            sourceReferenceId,
          } satisfies InsertJournalEntry)
          .returning();
        if (!entry) throw new Error("Failed to write the recurring entry");

        await tx.insert(journalLineTable).values({
          journalEntryId: entry.id,
          accountId: recurring.accountId,
          debit: Number(recurring.amount).toFixed(4),
          credit: "0.0000",
        } satisfies InsertJournalLine);
        await tx.insert(journalLineTable).values({
          journalEntryId: entry.id,
          accountId: counterAccountId,
          debit: "0.0000",
          credit: Number(recurring.amount).toFixed(4),
        } satisfies InsertJournalLine);
      });
      posted += 1;
    }

    dueDate = advanceDate(dueDate, recurring.frequency as RecurringFrequency);
  }

  await dbPool
    .update(recurringTransactionTable)
    .set({
      nextExpectedDate: `${dueDate}T00:00:00.000Z`,
      updatedAt: new Date().toISOString(),
    })
    .where(eq(recurringTransactionTable.id, recurring.id));

  return {
    recurringTransactionId: recurring.id,
    posted,
    nextExpectedDate: dueDate,
  };
};

/**
 * Materialize all active, due recurring transactions (optionally for one book)
 * as of a date. Used by the scheduled runner and the manual run endpoint
 */
export const runDueRecurring = async (opts: {
  asOf: string;
  bookId?: string;
}): Promise<MaterializeResult[]> => {
  const { asOf, bookId } = opts;
  const due = await dbPool
    .select()
    .from(recurringTransactionTable)
    .where(
      bookId
        ? and(
            eq(recurringTransactionTable.bookId, bookId),
            eq(recurringTransactionTable.isActive, true),
            lte(
              recurringTransactionTable.nextExpectedDate,
              `${asOf}T23:59:59Z`,
            ),
          )
        : and(
            eq(recurringTransactionTable.isActive, true),
            lte(
              recurringTransactionTable.nextExpectedDate,
              `${asOf}T23:59:59Z`,
            ),
          ),
    );

  const results: MaterializeResult[] = [];
  for (const recurring of due) {
    results.push(await materializeRecurring(recurring, asOf));
  }
  return results;
};
